-- Nuevos tipos de documento (unidades + choferes)
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'HOMOLOGACION';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'OTRA_DOCUMENTACION';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'FOTO_VEHICULO';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'LICENCIA_FRENTE';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'LICENCIA_DORSO';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'SEGURO_ACCIDENTES';
