-- Foto del vehículo en 5 ángulos (FOTO_VEHICULO queda como "frente").
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'FOTO_ATRAS';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'FOTO_LATERAL_IZQ';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'FOTO_LATERAL_DER';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'FOTO_CARGA';
